# Generated by Django 5.1.7 on 2025-12-11 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('responce', models.TextField()),
                ('AI_Chatroom_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AI_Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ManyToManyField(to='STUDENT_STAGE_APIs.ai_prompt')),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_title', models.TextField(blank=True)),
                ('answer_body', models.TextField()),
                ('answer_image', models.ImageField(blank=True, upload_to='media/answer_images')),
                ('answer_feedback', models.TextField(blank=True)),
                ('tutor_answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='e_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_file', models.FileField(blank=True, null=True, upload_to='media/e_books_files')),
                ('book_poster', models.FileField(blank=True, null=True, upload_to='media/e_books_posters')),
                ('book_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('book_publisher', models.CharField(max_length=200)),
                ('book_summery', models.TextField(blank=True)),
                ('year_published', models.DateField(blank=True, null=True)),
                ('book_category', models.CharField(max_length=100)),
                ('book_origin', models.TextField(blank=True)),
                ('free_version', models.BooleanField(default=False)),
                ('user_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(blank=True)),
                ('news_body', models.TextField()),
                ('news_images', models.ImageField(blank=True, upload_to='media/news_images')),
                ('news_clip', models.FileField(blank=True, upload_to='media/news_clips')),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('category_raleted', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/profile_images')),
                ('address', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('marked_as', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(default='000000000', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, upload_to='media/questions_images')),
                ('date', models.DateTimeField(auto_now=True)),
                ('question_catagory', models.CharField(max_length=100)),
                ('answer_id', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STUDENT_STAGE_APIs.profile')),
                ('tutor_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_assign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notifiaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('feadback', models.TextField(null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='STUDENT_STAGE_APIs.answer')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STUDENT_STAGE_APIs.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STUDENT_STAGE_APIs.question'),
        ),
    ]
